

title: 马瑞贤的博客
email: 3035615685@qq.com
description: >- # this means to ignore newlines until "baseurl:"
  欢迎来到我的博客！
baseurl: "" 
url: "https://JacksonWang19.github.io" 
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed


paginate: 5
paginate_path: "/page:num/"


markdown: kramdown
theme: minima
plugins:
  - jekyll-feed


